### ISSUE TITLE
AttributeError: 'Module' object has no attribute 'get_marker'

### ISSUE THREAD

**Issue by visko-tm** [reportportal/agent-python-pytest#103]
System Version: macOS 10.14.2

test_calc.py:

```
from calc import Calc
class TestCalc(object):
    def test_plus(self):
        assert Calc().plus(2, 3) == 5

    def test_minus(self):
        assert Calc().minus(2, 3) == 5
```

pytest.ini:

```
[pytest]
rp_uuid = 2596195c-e886-4fac-a107-5751113b7cc2
rp_endpoint = http://localhost:8080
rp_project = test-poc
rp_launch = regression
```
Error:
```
platform darwin -- Python 3.7.2, pytest-4.1.1, py-1.7.0, pluggy-0.8.1
rootdir: /Users/visko/PycharmProjects/test-poc, inifile: pytest.ini
plugins: reportportal-1.0.4
collected 2 items
...
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytest_reportportal/listener.py", line 32, in pytest_runtest_protocol
INTERNALERROR>     self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytest_reportportal/service.py", line 200, in start_pytest_item
INTERNALERROR>     'tags': self._get_item_tags(part),
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytest_reportportal/service.py", line 416, in _get_item_tags
INTERNALERROR>     tags = [k for k in item.keywords if item.get_marker(k) is not None
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pytest_reportportal/service.py", line 416, in <listcomp>
INTERNALERROR>     tags = [k for k in item.keywords if item.get_marker(k) is not None
INTERNALERROR> AttributeError: 'Module' object has no attribute 'get_marker'
```

The test run (launch) is added to RP, but there are no test cases or results added (total 0). It is supposed to be a very simple basic setup.
Could you please check?

**Comment by eg4a** [comment]
+1
This happens to me too on Ubuntu 18.04.2 LTS and also on Windows 10.

Any test that I run with the switch '--reportportal' fails on the same issue when it transmits to the report portal end point.

_used packages version info:_

- reportportal-client version: 3.2.0
- pytest-reportportal version: 1.0.4
- pytest version: 4.2.0

_example pytest command :_
pytest -vss --reportportal

_local workaround that I use to overcome this:_
As a local hot-fix , in the service.py file I replaced 'item.get_marker' with 'item.get_closest_marker' on the _get_item_tags method.

Note that from what I saw, the latest revision of the master branch for the service.py file already uses 'item.get_closest_marker'.

Is there an estimate when to expect the next release of a newer version higher than 1.0.4 with this fix?

Thanks :-)

**Comment by SazonovDO** [comment]
+1 
I have this bug:

platform linux -- Python 3.6.7, pytest-4.3.0, py-1.5.2, pluggy-0.8.1
plugins: reportportal-1.0.4
collected 1 item                                                                                                                                                                                                                                                                                 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 210, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 250, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/_pytest/main.py", line 271, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/hooks.py", line 284, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pytest_reportportal/listener.py", line 32, in pytest_runtest_protocol
INTERNALERROR>     self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pytest_reportportal/service.py", line 200, in start_pytest_item
INTERNALERROR>     'tags': self._get_item_tags(part),
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pytest_reportportal/service.py", line 416, in _get_item_tags
INTERNALERROR>     tags = [k for k in item.keywords if item.get_marker(k) is not None
INTERNALERROR>   File "/usr/local/lib/python3.6/dist-packages/pytest_reportportal/service.py", line 416, in <listcomp>
INTERNALERROR>     tags = [k for k in item.keywords if item.get_marker(k) is not None
**INTERNALERROR> AttributeError: 'Module' object has no attribute 'get_marker'**

Thanks.

**Comment by akropyva-apixio** [comment]
> +1
> This happens to me too on Ubuntu 18.04.2 LTS and also on Windows 10.
> 
> Any test that I run with the switch '--reportportal' fails on the same issue when it transmits to the report portal end point.
> 
> _used packages version info:_
> 
> * reportportal-client version: 3.2.0
> * pytest-reportportal version: 1.0.4
> * pytest version: 4.2.0
> 
> _example pytest command :_
> 
> > pytest -vss --reportportal
> 
> _local workaround that I use to overcome this:_
> 
> As a local hot-fix , in the service.py file I replaced 'item.get_marker' with 'item.get_closest_marker' on the _get_item_tags method.
> 
> Note that from what I saw, the latest revision of the master branch for the service.py file already uses 'item.get_closest_marker'.
> 
> Is there an estimate when to expect the next release of a newer version higher than 1.0.4 with this fix?
> 
> Thanks :-)

Local fix helped thanks

**Comment by eg4a** [comment]
@akropyva-apixio
Happy that the local fix helped :-)
Hopefully a newer version will be released soon.

**Comment by akropyva-apixio** [comment]
It fixed this issue and issue with xdist
-e git+git@github.com:reportportal/client-Python.git#egg=reportportal_client
-e git+git@github.com:reportportal/agent-python-pytest.git#egg=pytest_reportportal

**Comment by imankovskyi** [comment]
should be happening for pytest >= 4.1.0 users
pytest 4.1.0 (2019-01-05)
`#4546: Remove Node.get_marker(name) the return value was not usable for more than a existence check.`

**Comment by DzmitryHumianiuk** [comment]
@visko-tm @imankovskyi @akropyva-apixio @eg4a @SazonovDO can we closed it?
fixed?

**Comment by eg4a** [comment]
Hi @DzmitryHumianiuk ,
The latest version I see for pytest-reportportal is still 1.0.4 , so this issue still reproduces.

Extracting from my initial comment here:

> Note that from what I saw, the latest revision of the master branch for the service.py file already uses 'item.get_closest_marker'.

> Is there an estimate when to expect the next release of a newer version higher than 1.0.4 with this fix?

**Comment by DzmitryHumianiuk** [comment]
@filland do we have release job for python agents?
Then should create it, if not.

**Comment by filland** [comment]
@DzmitryHumianiuk i am working on it

**Comment by trew100** [comment]
@filland There is already new version?

@imankovskyi how did you resolve this issue with xdist?

**Comment by imankovskyi** [comment]
issue does not reproduce on 4.0, I used that one

**Comment by trew100** [comment]
> 
> 
> issue does not reproduce on 4.0, I used that one

This issue reproduce for me Pytest == 4.4.1


```
platform linux -- Python 3.6.8, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /src/tests, inifile: pytest.ini
plugins: reportportal-1.0.4
collected 9 items
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 209, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 249, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/_pytest/main.py", line 270, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/hooks.py", line 289, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 68, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/manager.py", line 62, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_reportportal/listener.py", line 32, in pytest_runtest_protocol
INTERNALERROR>     self.PyTestService.start_pytest_item(item)
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_reportportal/service.py", line 200, in start_pytest_item
INTERNALERROR>     'tags': self._get_item_tags(part),
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_reportportal/service.py", line 416, in _get_item_tags
INTERNALERROR>     tags = [k for k in item.keywords if item.get_marker(k) is not None
INTERNALERROR>   File "/usr/local/lib/python3.6/site-packages/pytest_reportportal/service.py", line 416, in <listcomp>
INTERNALERROR>     tags = [k for k in item.keywords if item.get_marker(k) is not None
INTERNALERROR> AttributeError: 'Module' object has no attribute 'get_marker'
```

**Comment by vkolgi** [comment]
@DzmitryHumianiuk we are still relying on the workaround, can we release the next version soon. If any help needed for the testing do let us know.

**Comment by DzmitryHumianiuk** [comment]
@filland do you have access to release it?

**Comment by david-fliguer-ws** [comment]
Hi,

I am just trying to get a basic installation of reportportal running and run a simple test that makes assert == True and see the result in the dashboard

when running I get the following error:

INTERNALERROR>   File "/home/david.fliguer/.local/lib/python3.7/site-packages/pytest_reportportal/service.py", line 416, in <listcomp>
INTERNALERROR>     tags = [k for k in item.keywords if item.get_marker(k) is not None
INTERNALERROR> AttributeError: 'Module' object has no attribute 'get_marker'

Is this the same issue that is open here ?

Any way to solve it by now ?

I am running pytest version 4.6.0 and pytest-reportportal 1.0.4 (I know is not the latest but with the latest one I experienced other issues)

Thanks and hope someone can help 

Thanks,

David

**Comment by vkolgi** [comment]
@david-fliguer-ws here is what I did as a workaround if you stick to 1.4.0 version. Patched get_marker function in Node object. 

In your conftest.py define get_marker function and return get_closest_marker's result. 
```
def get_marker(self, name, default=None):
    return self.get_closest_marker(name, default)
```
And at the end of the `pytest_configure` function, add this.

```
    from _pytest.nodes import Node
    setattr(Node, 'get_marker', get_marker)
```

**Comment by david-fliguer-ws** [comment]
Hi, where is that pytest_configure function ?

**Comment by david-fliguer-ws** [comment]
I managed to at least be able to run the test and the test passes but then it just gets stucked

when I run the test with pytest the test passes but then it just gets stucked

I see in the output of the containers the following error:

analyzer_1 | [2019-06-04 05:28:56] ERROR Cannot send request to ES: Get http://elasticsearch:9200/_cluster/health: dial tcp: lookup elasticsearch on 127.0.0.11:53: no such host

Hope someone can help me

Thanks,

David

**Comment by chcheruk** [comment]
I am hitting the same issue. Any idea when this issue get fixed?

**Comment by DzmitryHumianiuk** [comment]
@chcheruk someone needs to contribute

**Comment by chcheruk** [comment]
@DzmitryHumianiuk Local fix mentioned above worked for me. I thought that is the fix and the master has that code. Any idea what else needs fix? Thanks

**Comment by iivanou** [comment]
@david-fliguer-ws, @chcheruk, I was not able to reproduce this with:
`metadata: {'Python': '3.6.5', 'Platform': 'Linux-3.10.0-693.11.6.el7.x86_64-x86_64-with-centos-7.6.1810-Core', 'Packages': {'pytest': '4.5.0', 'py': '1.5.3', 'pluggy': '0.11.0'}, 'Plugins': {'xdist': '1.24.1', 'rerunfailures': '5.0', 'reportportal': '1.0.8', 'metadata': '1.7.0', 'lazy-fixture': '0.5.2', 'html': '1.19.0', 'forked': '0.2', 'cov': '2.5.1'}}`

Can u try the latest version of the reportportal-client? The local fix modifies the structure of the class shipped by the Pytest package. That's not a good practice in development.

**Comment by iivanou** [comment]
Should have already been fixed in 1.0.9 version(commit: 0cb3f4e4).
